### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ByLife** [clipssender31/Discord-token-joiner#11]
What is the syntax to follow in “Proxies.txt” ?

xxx.proxy.com:8080:user:pass ?

**Comment by ByLife** [comment]
Because I put: gw.proxy.rainproxy.io:5959:fhz1oDe4kU-cc-any:PASSHERE
and it doesn't allow me to connect

**Comment by clipssender31** [comment]
It should be user:pass@host:port
