### ISSUE TITLE
Gives this error for some reason 

### ISSUE THREAD

**Issue by CTB64YT** [clipssender31/Discord-token-joiner#17]
Error: Expecting value: line 1 column 1 
![resim](https://user-images.githubusercontent.com/91343696/181863305-b3b9d10e-2e0f-4b50-a97f-edab796a1042.png)

**Comment by CTB64YT** [comment]
![resim](https://user-images.githubusercontent.com/91343696/181863409-5bf24344-6ec1-4966-937a-4342c88eb608.png)
I tried it without proxies. it gives the same error

**Comment by Scassinator88** [comment]
Have you solved this issue? It does the same thing to me
